name : github-action-demo

on:
  workflow_dispatch

  push:
    branches: ["master"]

jobs:
  runs-on: ubantu-latest
  
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: python demo.py
